### ISSUE TITLE
Use of angle brackets

### ISSUE THREAD

**Issue by rgaiacs** [gesistsa/usemh#12]
@chainsawriot pointed to me that [Checklist for CRAN submissions](https://cran.r-project.org/web/packages/submission_checklist.html) includes instructions for the use of angle brackets.

> - DOIs should be enclosed in angle brackets, and formatted as <doi:10.prefix/suffix>. Example: Sugihara (1994) <doi:10.1098/rsta.1994.0106>.
> - arXiv preprints should be referred to via their arXiv DOI, <doi:10.48550/arXiv.ID>, where ID is the unversioned arXiv identifier. Example: Srivastava et al. (2011) <doi:10.48550/arXiv.1103.3817>. 

CommonMark and Pandoc's Markdown use angle brackets for automatic links, see [Autolink section in CommonMark Specification](https://spec.commonmark.org/0.31.2/#autolink) and [Automatic Links in Pandoc User's Guide](https://pandoc.org/MANUAL.html#automatic-links).

```bash
pandoc -f markdown -t html --wrap=none <<EOF
Sugihara (1994) <doi:10.1098/rsta.1994.0106>.
EOF
```

produces

```html
<p>Sugihara (1994) <a href="doi:10.1098/rsta.1994.0106" class="uri">doi:10.1098/rsta.1994.0106</a>.</p>
```

instead of the desired

```html
<p>Sugihara (1994) <a href=" https://doi.org/10.1098/rsta.1994.0106" class="uri">doi:10.1098/rsta.1994.0106</a>.</p>
```

`usemh` is converting

```
Sugihara (1994) <doi:10.1098/rsta.1994.0106>.
```

to

```markdown
Sugihara (1994) [<doi:10.1098/rsta.1994.0106>](https://doi.org/10.1098/rsta.1994.0106).
```

that Pandoc later converts to

```html
<p>Sugihara (1994) <a href="https://doi.org/10.1098/rsta.1994.0106">&lt;doi:10.1098/rsta.1994.0106&gt;</a>.</p>
```

First, @chainsawriot and @schochastics is the `&lt;` and `&gt;` necessary for Methods Hub?

If we use another Markdown to HTML, for example [markdown-it-py](https://github.com/executablebooks/markdown-it-py), the output is

```html
<p>Sugihara (1994) <a href="https://doi.org/10.1098/rsta.1994.0106"><a href="doi:10.1098/rsta.1994.0106">doi:10.1098/rsta.1994.0106</a></a>.</p>\n
```

because they don't sanitise the `<` and `<`.

@schochastics and @chainsawriot can we avoid ambiguity for the Markdown parser?

**Comment by chainsawriot** [comment]
To me, it's not essential. As I wrote this, it's there just to emulate the output on CRAN.

https://cloud.r-project.org/web/packages/oolong/index.html

If it conflicts with other markdown renderers, I am fine with removing the angle brackets. So the generated markdown and HTML would be:

```bash
pandoc -f markdown -t html --wrap=none <<EOF
Sugihara (1994) [doi:10.1098/rsta.1994.0106](https://doi.org/10.1098/rsta.1994.0106).
EOF
```

```html
<p>Sugihara (1994) <a href="https://doi.org/10.1098/rsta.1994.0106">doi:10.1098/rsta.1994.0106</a>.</p>
```

The fix pertains to just one line:

https://github.com/gesistsa/usemh/blob/cb720f6c0403ae134c26ec0861b2ee2a5de1a9ab/R/usemh_method.R#L83

**Comment by chainsawriot** [comment]
I can foresee that #7 will also be a problem.

**Comment by chainsawriot** [comment]
- [x] Stop emitting angle brackets for dois #13 
- [x] Stop emitting angle brackets for arxiv
- [x] Check and fix all existing generated `methodshub.qmd`
    - [x] `sweater`
    - [x] `oolong`
    - [x] `rtoot`
    - [x] `webbotparseR`
    - [x] `webtrackR`
