### ISSUE TITLE
Bootstrap a tutorial repository

### ISSUE THREAD

**Issue by chainsawriot** [gesistsa/usemh#6]
As said. Not just for Method entries.

**Comment by schochastics** [comment]
@chainsawriot you mean a `use_mh()` for tutorials? Should probably work more like rang. Write your tutorial and once done, run the function and automatically extract the necessary information. Is that something? If have now enough tutorials ready which are anying to manually add the MH stuff. I can give such a function a try if thats ok

**Comment by chainsawriot** [comment]
Something like that. It can either use for bootstrapping (just copy the template and open it) and when rerun, running it like `rang` and it will generate "install.R" and stuff.

In comparison to `rang`, it should be easier because we can even do things like

```r
deps <- unique(renv::dependencies(".")$Package)
reqs <- remotes::system_requirements("ubuntu", "22.04", package = deps)
z <- lapply(reqs, system)

```

**Comment by schochastics** [comment]
Yes something like that I had in mind. I will draft something. I'd rather do that than adding those things manually to my tutorial :laughing:.

**Comment by schochastics** [comment]
quick question on system dependencies: Do they need to be declared in apt.txt? 
why is the third line `z <- lapply(reqs, system)` needed? Wouldn't that install the reqs on my machine?

My limited understanding was that the output of reqs would need to go to apt.txt, but I get that this is only for binder, yet the dependencies need to be declared for the install.R too somewhere?

**Comment by chainsawriot** [comment]
For the system deps, one can either do it in `apt.txt` or `install.R` (before those `install.packages()` calls, of course). Of course, you can just output `reqs` to `apt.txt`.
